name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  http: ^1.2.1
  anim_search_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.1
  weather_icons: ^3.0.0
  icon_forest: ^1.1.8
  font_awesome_flutter: ^9.2.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  bootstrap_icons: ^1.11.3
  animated_search_bar: ^2.7.1


flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "https://res.cloudinary.com/abhinithame/image/upload/v1712706546/Ramanan/Weather-Elite.png"
  image_path_ios: "https://res.cloudinary.com/abhinithame/image/upload/v1712706546/Ramanan/Weather-Elite.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "https://res.cloudinary.com/abhinithame/image/upload/v1712706546/Ramanan/Weather-Elite.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "https://res.cloudinary.com/abhinithame/image/upload/v1712706546/Ramanan/Weather-Elite.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "https://res.cloudinary.com/abhinithame/image/upload/v1712706546/Ramanan/Weather-Elite.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
